In [1]:
%pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\pyserial-3.5-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import cv2

In [3]:
images = []
labels = []
folder=r"./dogcatTrain"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder, filename))
    if img is not None:
        img = cv2.resize(img, (32, 32)) 
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
        images.append(img.flatten())
        label = 0 if 'cat' in filename else 1
        labels.append(label)

In [4]:
images[0]

array([174, 185, 196, ...,   4,   3,   3], dtype=uint8)

In [5]:
labels[0]

0

In [6]:
x=np.asarray(images)
y=np.asarray(labels)
print(x.shape)
y.shape

(25000, 1024)


(25000,)

In [7]:
from sklearn.svm import SVC
sm=SVC()
sm.fit(x,y)

SVC()

In [8]:
images = []
folder=r"./dogcatTest1"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder, filename))
    if img is not None:
        img = cv2.resize(img, (32, 32))  
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
        images.append(img.flatten())
        

In [9]:
x_test=np.asarray(images)
x_test.shape

(12500, 1024)

In [10]:
y_pred=sm.predict(x_test)
y_pred

array([0, 0, 0, ..., 1, 0, 1])

In [11]:
test_y=pd.read_csv("sampleSubmission3.csv")
y_test=test_y.iloc[:,1]
y_test

0        0
1        0
2        0
3        0
4        0
        ..
12495    0
12496    0
12497    0
12498    0
12499    0
Name: label, Length: 12500, dtype: int64

In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[5890, 6610],
       [   0,    0]], dtype=int64)

In [13]:
score=accuracy_score(y_test,y_pred)
score

0.4712